export const GalleryData = [
    {
        id:1,
        kategori:"Mountain",
        image:"./images/m1.jpg",
        name:"mountain"
    },
    {
        id:14,
        kategori:"Food",
        image:"./images/f2.jpg",
        name:"food"
    }, {
        id:10,
        kategori:"Birds",
        image:"./images/n2.jpg",
        name:"bird"
    },
    {
        id:3,
        kategori:"Mountain",
        image:"./images/m3.jpg",
        name:"mountain"
    },
   
    
    {
        id:5,
        kategori:"Beaches",
        image:"./images/b1.jpg",
        name:"beach"
    },
    {
        id:15,
        kategori:"Food",
        image:"./images/f3.jpg",
        name:"food"
    },
    {
        id:6,
        kategori:"Beaches",
        image:"./images/b2.jpg",
        name:"beach"
    },
   
    {
        id:8,
        kategori:"Beaches",
        image:"./images/b4.jpg",
        name:"beach"
    },
    {
        id:4,
        kategori:"Mountain",
        image:"./images/m4.jpg",
        name:"mountain"
    },
    {
        id:9,
        kategori:"Birds",
        image:"./images/n1.jpg",
        name:"bird"
    },
   
    {
        id:7,
        kategori:"Beaches",
        image:"./images/b3.jpg",
        name:"beach"
    },
    {
        id:11,
        kategori:"Birds",
        image:"./images/n3.jpg",
        name:"bird"
    },
   
    {
        id:13,
        kategori:"Food",
        image:"./images/f1.jpg",
        name:"food"
    },
    {
        id:2,
        kategori:"Mountain",
        image:"./images/m2.jpg",
        name:"mountain"
    },
  
    {
        id:12,
        kategori:"Birds",
        image:"./images/n4.jpg",
        name:"bird"
    },
    {
        id:16,
        kategori:"Food",
        image:"./images/f4.jpg",
        name:"food"
    },
   
]